# Docker 이미지 레지스트리
registry: localhost:5000

# BE 서비스별 이미지 태그 (Jenkins BE 파이프라인에서 변경된 서비스만 업데이트)
gatewayImageTag: "21"
userCommandImageTag: "9"
userQueryImageTag: "9"
emailImageTag: "23"
keycloakImageTag: "25"

# FE 이미지 태그 (Jenkins FE 파이프라인에서 자동 업데이트)
feImageTag: "17"

# Live 서비스 이미지 태그 (Jenkins BE 파이프라인에서 자동 업데이트)
liveCommandImageTag: "15"
liveQueryImageTag: "15"
chatImageTag: "15"
communityImageTag: "15"
