apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
  namespace: dev
spec:
  serviceName: user-postgres
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "user_service"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USER_DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USER_DB_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "userservice", "-d", "user_service"]
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "48Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  namespace: dev
spec:
  selector:
    app: user-postgres
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
