aws_region   = "ap-northeast-2"
cluster_name = "now-n-go-cluster"

ecr_repositories = [
  # infra service
  "elasticsearch",

  # data service
  "gateway-service",
  "user-write-service",
  "user-read-service",
  "products-write-service",
  "products-read-service",
  "skus-write-service",
  "skus-read-service",
  "sku-flights-write-service",
  "sku-flights-read-service",
  "sku-leisure-write-service",
  "sku-leisure-read-service",
  "sku-landmark-write-service",
  "sku-landmark-read-service",
  "sku-stay-write-service",
  "sku-stay-read-service",
  "sku-show-write-service",
  "sku-show-read-service",
  "sku-transport-write-service",
  "sku-transport-read-service",
  "orders-write-service",
  "orders-read-service",
  "order-items-write-service",
  "order-items-read-service",
  "payments-write-service",
  "payments-read-service",
  "location-write-service",
  "location-read-service",
  "review-write-service",
  "review-read-service",
  "seat-write-service",
  "seat-read-service",
  "media-data",

  # domain service
  "user-command-service",
  "email-service",
  "products-create-service",
  "products-list-service",
  "create-stay-product-service",
  "create-transport-product-service",
  "create-flight-product-service",
  "reviews-create-service",
  "reviews-list-service",
  "wishlist-service",
  "reservation-travel-service",
  "publish-order-service",
  "save-payments-service",
  "toss-payments-service",
  "get-skus-detail-service",
  "product-seat-list-service",
  "location-list-service",
  "bill-management-service",
  "data-bastion-service",
  "travel-ai",
]
