apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  # Keycloak
  KEYCLOAK_INTERNAL_URL: "http://keycloak:8080"
  KEYCLOAK_EXTERNAL_URL: "http://localhost:9090"
  KEYCLOAK_REALM: "Ticket-Service-Realm"
  KEYCLOAK_CLIENT_ID: "bff-client"
  KC_DB_URL: "jdbc:postgresql://postgres-keycloak:5432/keycloak"

  # Kafka (auth)
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  # Redis (auth)
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # User DB
  USER_DB_HOST: "user-postgres"
  USER_DB_PORT: "5432"

  # SMTP
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"

  # Kafka (business)
  KAFKA_BUSINESS_BOOTSTRAP_SERVERS: "kafka-business:9092"

  # Redis (business)
  REDIS_BUSINESS_HOST: "redis-business"
  REDIS_BUSINESS_PORT: "6379"

  # Booking DB
  BOOKING_DB_HOST: "postgres-booking"
  BOOKING_DB_PORT: "5432"

  # Product DB
  PRODUCT_DB_HOST: "postgres-products"
  PRODUCT_DB_PORT: "5432"

  # Social Login
  SOCIAL_LOGIN_SUCCESS_URL: "https://localhost:3000/dashboard"
  SOCIAL_LOGIN_ERROR_URL: "https://localhost:3000/login"
  SOCIAL_CALLBACK_BASE_URL: "http://localhost:8443"

  # S3 (MinIO)
  S3_ENDPOINT: "https://minio:9000"
  S3_PUBLIC_ENDPOINT: "https://localhost:9000"
  S3_REGION: "us-east-1"
  S3_BUCKET: "user-profiles"
  S3_TRUST_ALL_CERTS: "true"
