apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email-service
        image: localhost:5000/email-service:21
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m -XX:+UseSerialGC -XX:MaxMetaspaceSize=96m"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: REDIS_PASSWORD
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SMTP_PASSWORD
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: dev
spec:
  selector:
    app: email-service
  ports:
  - port: 8085
    targetPort: 8085
