apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
stringData:
  # Keycloak DB
  POSTGRES_USER: "keycloak"
  POSTGRES_PASSWORD: "keycloak1234"

  # Keycloak Admin
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"

  # BFF Client
  KEYCLOAK_CLIENT_SECRET: "bff-secret-local-dev"

  # Redis (auth)
  REDIS_PASSWORD: "redis-secret"

  # User DB
  USER_DB_USER: "userservice"
  USER_DB_PASSWORD: "userservice1234"

  # SMTP
  SMTP_USER: "waninokow@gmail.com"
  SMTP_PASSWORD: "urdh iuzk rntm ucyv"
  SMTP_FROM: "waninokow@gmail.com"
  SMTP_FROM_DISPLAY_NAME: "Ticket-Service"

  # Internal API Key (서비스 간 통신)
  INTERNAL_API_KEY: "k8s-internal-api-key-s3cur3"

  # Google OAuth
  GOOGLE_CLIENT_ID: "140364443613-ff37u5fg1vbo114p5ah1pfn6erjhug99.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"

  # Redis (business)
  REDIS_BUSINESS_PASSWORD: "redis-biz-secret"

  # Booking DB
  BOOKING_DB_USER: "bookingservice"
  BOOKING_DB_PASSWORD: "bookingservice1234"

  # Encryption Keys (AES-256 + HMAC)
  ENCRYPTION_AES_KEY: "gdP8yw1/oi3NNCfC5H/2/URZrhzSONpt8K/cCB1F9gk="
  ENCRYPTION_HMAC_KEY: "6ZtrrKC4Tg5NLKFPf1g8oivr64bNSJIXHpeJfE/Xcws="

  # S3 (MinIO)
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin1234"
