apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-query-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-query-service
  template:
    metadata:
      labels:
        app: user-query-service
    spec:
      containers:
      - name: user-query-service
        image: localhost:5000/user-query-service:27
        imagePullPolicy: Always
        ports:
        - containerPort: 8087
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m -XX:+UseSerialGC -XX:MaxMetaspaceSize=96m"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: INTERNAL_API_KEY
        - name: USER_READ_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_READ_SERVICE_URL
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-query-service
  namespace: dev
spec:
  selector:
    app: user-query-service
  ports:
  - port: 8087
    targetPort: 8087
