apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-write-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-write-service
  template:
    metadata:
      labels:
        app: user-write-service
    spec:
      containers:
      - name: user-write-service
        image: localhost:5000/user-write-service:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8188
        env:
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m -XX:+UseSerialGC -XX:MaxMetaspaceSize=96m"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: USER_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_DB_HOST
        - name: USER_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_DB_PORT
        - name: USER_DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USER_DB_USER
        - name: USER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USER_DB_PASSWORD
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: INTERNAL_API_KEY
        - name: ENCRYPTION_AES_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: ENCRYPTION_AES_KEY
        - name: ENCRYPTION_HMAC_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: ENCRYPTION_HMAC_KEY
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8188
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-write-service
  namespace: dev
spec:
  selector:
    app: user-write-service
  ports:
  - port: 8188
    targetPort: 8188
